version: '3.8'

volumes:
  fooocus-data:

services:
  app:
    build: .
    image: ghcr.io/lllyasviel/fooocus
    ports:
      - "7865:7865"
    environment:
      - CMDARGS=--listen                  # Arguments for launch.py
      - DATADIR=/content/data             # Directory storing models and output
      - config_path=/content/data/config.txt
      - config_example_path=/content/data/config_modification_tutorial.txt
      - path_checkpoints=/content/data/models/checkpoints/
      - path_loras=/content/data/models/loras/
      - path_embeddings=/content/data/models/embeddings/
      - path_vae_approx=/content/data/models/vae_approx/
      - path_upscale_models=/content/data/models/upscale_models/
      - path_inpaint=/content/data/models/inpaint/
      - path_controlnet=/content/data/models/controlnet/
      - path_clip_vision=/content/data/models/clip_vision/
      - path_fooocus_expansion=/content/data/models/prompt_expansion/fooocus_expansion/
      - path_outputs=/content/app/outputs/  # History log location under /content/app
    volumes:
      - fooocus-data:/content/data       # Mount the fooocus-data volume for persistent storage
      #- ./models:/import/models         # Uncomment to mount models directory if needed
      #- ./outputs:/import/outputs       # Uncomment to mount outputs directory if needed
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']            # Use GPU 0
              capabilities: [compute, utility]
